version: '3.7'
services:

  url-carver-go:
    container_name: url_carver_go
    image: golang:1.18-alpine
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - backend
    environment:
      - app_name="URL carver"
      - port=8080
    volumes:
      - ../:/app
    working_dir: /app
    command: sh -c "apk update && apk --no-cache --update add build-base && go run cmd/shortener/main.go"

  url-carver-go-doc:
    container_name: url_carver_go_doc
    image: golang:1.18-alpine
    ports:
      - "${DOC_PORT}:${DOC_PORT}"
    networks:
      - backend
    volumes:
      - ../:/app
    working_dir: /app
    depends_on:
      - url-carver-go
    command: sh -c "go install -v golang.org/x/tools/cmd/godoc@latest && godoc -http=:${DOC_PORT}"

  postgres:
    container_name: postgres_container
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_DB: "postgresql"
      POSTGRES_USER: "postgresql_user"
      POSTGRES_PASSWORD: "user_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgresql_user -d postgresql" ]
      timeout: 45s
      interval: 2s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - backend
networks:
  backend:
    driver: bridge